- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.1.29
  hooks:
    - id: nbqa
      args: ['black', '--nbqa-mutate']
      name: nbqa-black
      additional_dependencies: ['black']
      files: \.ipynb$
    - id: nbqa
      args: ['flake8', '--ignore=E501']
      name: nbqa-flake8
      additional_dependencies: ['flake8']
      files: \.ipynb$
    - id: nbqa
      args: ['isort', '--nbqa-mutate']
      name: nbqa-isort
      additional_dependencies: ['isort']
      files: \.ipynb$
- repo: local
  hooks:
    - id: jupyter-nb-clear-output
      name: jupyter-nb-clear-output
      files: \.ipynb$
      language: system
      entry: jupyter nbconvert --clear-output --inplace
